/**
 * Permission Decision Handler
 *
 * Handles permission_decision WebSocket messages from Discord bot.
 * This is the new permission system that supports scopes and suggestions.
 */

import type { PluginSession } from '../plugins/index.js';
import type { WebSocketManager } from '../websocket.js';

export interface PermissionDecisionHandlerDeps {
    cliSessions: Map<string, PluginSession>;
    wsManager: WebSocketManager;
}

export interface PermissionDecisionData {
    requestId: string;
    sessionId?: string; // Explicit session ID from newer bots
    behavior: 'allow' | 'deny';
    scope?: 'session' | 'localSettings' | 'userSettings' | 'projectSettings';
    updatedPermissions?: any[];
    customMessage?: string;
}

/**
 * Handle permission decision from Discord bot
 */
export async function handlePermissionDecision(
    data: PermissionDecisionData,
    deps: PermissionDecisionHandlerDeps
): Promise<void> {
    const { cliSessions, wsManager } = deps;
    const { requestId, behavior, scope, updatedPermissions, customMessage } = data;

    console.log(`[PermissionDecision] Received decision for request ${requestId}: ${behavior}`);

    // The requestId is generated by discord-bot and needs to be mapped to a session
    // The format is typically: sessionId-timestamp
    // We need to find the session that corresponds to this request

    // Try to extract sessionId from requestId
    // The discord-bot creates requestId as: sessionId + '-' + timestamp
    // Ideally use the explicit sessionId if provided
    let sessionId = data.sessionId;
    
    if (!sessionId) {
        // Fallback: This is risky for UUIDs but kept for legacy
        sessionId = requestId.split('-')[0];
        // If it looks like a short hash (8 chars), it might be right. 
        // If it's part of a UUID (8 chars), it might conform to short ID lookup logic?
    }
    
    // Try explicit lookup first (full ID)
    let session = cliSessions.get(sessionId);
    
    // If not found, tries by short ID if sessionId is length 8? 
    // Or if split returned just one part.
    if (!session && sessionId && sessionId.length === 8) {
         // Maybe iteration happens elsewhere? No.
    }

    if (!session) {
        console.error(`[PermissionDecision] Session not found for requestId: ${requestId}`);
        return;
    }

    // Check if this is a ClaudeSDKPlugin session with sendPermissionDecision method
    if ('sendPermissionDecision' in session && typeof session.sendPermissionDecision === 'function') {
        try {
            await (session as any).sendPermissionDecision(requestId, {
                behavior,
                scope,
                updatedPermissions,
                updatedInput: undefined, // Not provided by discord-bot in this flow
                message: customMessage
            });

            console.log(`[PermissionDecision] Sent decision to session ${sessionId}`);
        } catch (error) {
            console.error(`[PermissionDecision] Failed to send decision to session ${sessionId}:`, error);
        }
    } else {
        console.error(`[PermissionDecision] Session ${sessionId} does not support sendPermissionDecision`);
    }
}
